// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfttiivquxhdfubjmkha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdHRpaXZxdXhoZGZ1Ympta2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjE3NzMsImV4cCI6MjA2OTgzNzc3M30.gNuBTAoyd-a7bry0O2GI5I5GScfBEegdCLft50r_5r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});